# Generated by Django 3.0.8 on 2020-08-04 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpi_input',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
