# Generated by Django 3.0.8 on 2020-08-04 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpi_input',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kpi_input',
            name='kpi_id',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='kpi_prov',
            name='kpi_id',
            field=models.CharField(max_length=5),
        ),
    ]
