# Generated by Django 3.0.8 on 2020-08-04 08:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200804_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kpi_input_null',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kpi_id', models.CharField(max_length=5)),
                ('hospcode', models.CharField(max_length=5)),
                ('kpi_month', models.DateField()),
                ('kpi_year', models.DateField(blank=True, null=True)),
                ('a1', models.CharField(max_length=155)),
                ('b1', models.CharField(max_length=155)),
                ('a2', models.CharField(max_length=155)),
                ('b2', models.CharField(max_length=155)),
                ('a3', models.CharField(max_length=155)),
                ('b3', models.CharField(max_length=155)),
                ('a4', models.CharField(max_length=155)),
                ('b4', models.CharField(max_length=155)),
                ('a5', models.CharField(max_length=155)),
                ('b5', models.CharField(max_length=155)),
                ('a6', models.CharField(max_length=155)),
                ('b6', models.CharField(max_length=155)),
                ('a7', models.CharField(max_length=155)),
                ('b7', models.CharField(max_length=155)),
                ('a8', models.CharField(max_length=155)),
                ('b8', models.CharField(max_length=155)),
                ('a9', models.CharField(max_length=155)),
                ('b9', models.CharField(max_length=155)),
                ('a10', models.CharField(max_length=155)),
                ('b10', models.CharField(max_length=155)),
                ('a11', models.CharField(max_length=155)),
                ('b11', models.CharField(max_length=155)),
                ('a12', models.CharField(max_length=155)),
                ('b12', models.CharField(max_length=155)),
                ('etc', models.TextField()),
                ('kpi_value', models.CharField(max_length=15)),
                ('d_update', models.DateTimeField(default=django.utils.timezone.now)),
                ('input_date', models.DateTimeField()),
                ('note', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
